### ISSUE TITLE
Wanted a C programme that trim a selected keyword from the string

### ISSUE THREAD

**Issue by Sneha-Singh18** [Sneha-Singh18/School-Programme#1]
Need a C programme that trim a selected keyword from the string.
Example:
We need to trim word: Programme
Given String: This programme contains code of C language
Required Output: This contains code of C language

**Comment by ZeelParekh10** [comment]
I would like to contribute in this issue, please assign this to me

**Comment by Sneha-Singh18** [comment]
Assigned

**Comment by rituraj-OO7** [comment]
plz assign it to me
